<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

<!--libgazebo_ros_tricycle_drive.so       libmy_controller_lib.so-->
  <xacro:macro name="tricycle_drive">
    <gazebo>
        <plugin name="tricycle_drive_controller" filename=" libmy_controller_lib.so ">
            <rosDebugLevel>Debug</rosDebugLevel>
            <robotNamespace></robotNamespace>
            <publishWheelTF>false</publishWheelTF>
            <publishWheelJointState>true</publishWheelJointState>
            <alwaysOn>true</alwaysOn>
            <steeringJoint>front_steering_joint</steeringJoint>
            <actuatedWheelJoint>front_wheel_joint</actuatedWheelJoint>
            <encoderWheelLeftJoint>left_wheel_joint</encoderWheelLeftJoint>
            <encoderWheelRightJoint>right_wheel_joint</encoderWheelRightJoint>
            <actuatedWheelDiameter>0.11</actuatedWheelDiameter>
            <encoderWheelDiameter>0.11</encoderWheelDiameter>
            <encoderWheelSeparation>0.66</encoderWheelSeparation>
            <commandTopic>cmd_vel</commandTopic>
            <odometryTopic>odom</odometryTopic>
            <odometryFrame>odom</odometryFrame>
            <odometrySource>world</odometrySource>
            <robotBaseFrame>base_link</robotBaseFrame>
            <updateRate>10.0</updateRate>
            <wheelAcceleration>0</wheelAcceleration>
            <wheelDeceleration>0</wheelDeceleration>
            <wheelSpeedTolerance>0.001</wheelSpeedTolerance>
            <wheelTorque>20</wheelTorque>
            <steeringSpeed>1.5</steeringSpeed>
            <steeringAngleTolerance>0.01</steeringAngleTolerance>
        </plugin>
    </gazebo>
  </xacro:macro>

  <xacro:macro name="differential_drive">
        <gazebo>
            <plugin name="differential_drive_controller" 
                    filename="libgazebo_ros_diff_drive.so">
                <rosDebugLevel>Debug</rosDebugLevel>
                <publishWheelTF>true</publishWheelTF>
                <robotNamespace>/</robotNamespace>
                <publishTf>1</publishTf>
                <publishWheelJointState>true</publishWheelJointState>
                <alwaysOn>true</alwaysOn>
                <updateRate>100.0</updateRate>
                <legacyMode>true</legacyMode>
                <leftJoint>left_wheel_joint</leftJoint>
                <rightJoint>right_wheel_joint</rightJoint>
                <wheelSeparation>${DY}</wheelSeparation>
                <wheelDiameter>${2*radius_actuated_wheel}</wheelDiameter>
                <broadcastTF>1</broadcastTF>
                <wheelTorque>30</wheelTorque>
                <wheelAcceleration>1.8</wheelAcceleration>
                <commandTopic>cmd_vel</commandTopic>
                <odometryFrame>odom</odometryFrame> 
                <odometryTopic>odom</odometryTopic> 
                <robotBaseFrame>base_link</robotBaseFrame>
            </plugin>
        </gazebo> 
  </xacro:macro>

</robot>
